// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConfigEditor: typeof import('./src/components/ConfigEditor/ConfigEditor.vue')['default']
    CourseEditor: typeof import('./src/components/CourseTable/CourseEditor/CourseEditor.vue')['default']
    CourseTable: typeof import('./src/components/CourseTable/CourseTable.vue')['default']
    Docs: typeof import('./src/components/Docs/Docs.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDivider: typeof import('naive-ui')['NDivider']
    NDynamicInput: typeof import('naive-ui')['NDynamicInput']
    NInput: typeof import('naive-ui')['NInput']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NTransfer: typeof import('naive-ui')['NTransfer']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SituationEditor: typeof import('./src/components/CourseTable/CourseEditor/SituationEditor.vue')['default']
    TopTabBar: typeof import('./src/components/TopTabBar.vue')['default']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    WeekSelector: typeof import('./src/components/CourseTable/CourseEditor/WeekSelector.vue')['default']
  }
}
